export const BUSINESS_RULES = {
  TAX: {
    DEFAULT_RATE: 16.0,
    IVA_RATE: 16.0,
    MAX_ITEM_DISCOUNT_PERCENT: 100,
  },
  SALES: {
    MAX_ITEMS_PER_TICKET: 999,
    GRACE_PERIOD_MINUTES: 15,
    MINIMUM_CASH_AMOUNT: 0.01,
    DEFAULT_CURRENCY: 'USD',
    LOCAL_CURRENCY: 'VES',
  },
  SHIFT: {
    MAX_OPEN_HOURS: 24,
    REQUIRED_OPENING_CASH_MIN: 0,
  },
  LOYALTY: {
    GEMS_PER_SALE_BASE: 5,
    GEMS_REDEEM_RATIO: 10,
    GEMS_DOLLAR_VALUE: 1.0,
  },
  XP: {
    BASE_SALE_XP: 10,
    XP_PER_DOLLAR_FACTOR: 0.25,
    SHIFT_CLOSE_XP: 25,
  },
} as const;
