export interface EventRegistration {
  eventName: string;
  description: string;
  sourceModule: string;
  subscribes: string[];
  payloadType: string;
  version: number;
}

export const EVENT_REGISTRY: Record<string, EventRegistration> = {
  'auth:user_login': {
    eventName: 'auth:user_login',
    description: 'Un usuario ha iniciado sesión en el sistema',
    sourceModule: 'auth',
    subscribes: ['gamification', 'dashboard', 'settings'],
    payloadType: '{ userId: string; username: string }',
    version: 1,
  },
  'auth:user_logout': {
    eventName: 'auth:user_logout',
    description: 'Un usuario ha cerrado sesión',
    sourceModule: 'auth',
    subscribes: [],
    payloadType: '{ userId: string }',
    version: 1,
  },
  'sales:sale_completed': {
    eventName: 'sales:sale_completed',
    description: 'Una venta ha sido completada exitosamente en el POS',
    sourceModule: 'sales',
    subscribes: ['inventory', 'gamification', 'fiscal', 'customers', 'shifts', 'dashboard'],
    payloadType: 'SaleCompletedPayload',
    version: 1,
  },
  'inventory:stock_changed': {
    eventName: 'inventory:stock_changed',
    description: 'El stock de un producto ha sido modificado',
    sourceModule: 'inventory',
    subscribes: ['dashboard', 'logistics'],
    payloadType: 'StockChangedPayload',
    version: 1,
  },
  'inventory:product_created': {
    eventName: 'inventory:product_created',
    description: 'Un nuevo producto ha sido creado en el catálogo',
    sourceModule: 'inventory',
    subscribes: ['dashboard'],
    payloadType: 'ProductCreatedPayload',
    version: 1,
  },
  'inventory:product_updated': {
    eventName: 'inventory:product_updated',
    description: 'Un producto existente ha sido actualizado',
    sourceModule: 'inventory',
    subscribes: ['dashboard'],
    payloadType: 'ProductUpdatedPayload',
    version: 1,
  },
  'inventory:product_deleted': {
    eventName: 'inventory:product_deleted',
    description: 'Un producto ha sido eliminado del catálogo',
    sourceModule: 'inventory',
    subscribes: ['dashboard'],
    payloadType: 'ProductDeletedPayload',
    version: 1,
  },
  'customers:customer_created': {
    eventName: 'customers:customer_created',
    description: 'Un nuevo cliente ha sido registrado',
    sourceModule: 'customers',
    subscribes: ['dashboard'],
    payloadType: 'CustomerCreatedPayload',
    version: 1,
  },
  'customers:customer_updated': {
    eventName: 'customers:customer_updated',
    description: 'Los datos de un cliente han sido actualizados',
    sourceModule: 'customers',
    subscribes: [],
    payloadType: 'CustomerUpdatedPayload',
    version: 1,
  },
  'customers:customer_deleted': {
    eventName: 'customers:customer_deleted',
    description: 'Un cliente ha sido eliminado del sistema',
    sourceModule: 'customers',
    subscribes: ['dashboard'],
    payloadType: 'CustomerDeletedPayload',
    version: 1,
  },
  'customers:loyalty_points_changed': {
    eventName: 'customers:loyalty_points_changed',
    description: 'Los puntos de fidelidad de un cliente han cambiado',
    sourceModule: 'customers',
    subscribes: ['gamification', 'sales'],
    payloadType: 'LoyaltyPointsChangedPayload',
    version: 1,
  },
  'shifts:shift_opened': {
    eventName: 'shifts:shift_opened',
    description: 'Un turno de caja ha sido abierto',
    sourceModule: 'shifts',
    subscribes: ['dashboard', 'audit'],
    payloadType: 'ShiftOpenedPayload',
    version: 1,
  },
  'shifts:shift_closed': {
    eventName: 'shifts:shift_closed',
    description: 'Un turno de caja ha sido cerrado',
    sourceModule: 'shifts',
    subscribes: ['dashboard', 'audit'],
    payloadType: 'ShiftClosedPayload',
    version: 1,
  },
  'shifts:shift_movement_added': {
    eventName: 'shifts:shift_movement_added',
    description: 'Se ha registrado un movimiento de efectivo en el turno',
    sourceModule: 'shifts',
    subscribes: [],
    payloadType: 'ShiftMovementAddedPayload',
    version: 1,
  },
  'gamification:xp_earned': {
    eventName: 'gamification:xp_earned',
    description: 'Un usuario ha ganado puntos de experiencia',
    sourceModule: 'gamification',
    subscribes: ['dashboard', 'auth'],
    payloadType: 'XpEarnedPayload',
    version: 1,
  },
  'gamification:level_up': {
    eventName: 'gamification:level_up',
    description: 'Un usuario ha subido de nivel',
    sourceModule: 'gamification',
    subscribes: ['dashboard', 'auth'],
    payloadType: 'LevelUpPayload',
    version: 1,
  },
  'gamification:gems_changed': {
    eventName: 'gamification:gems_changed',
    description: 'La cantidad de gemas de un usuario ha cambiado',
    sourceModule: 'gamification',
    subscribes: ['dashboard'],
    payloadType: 'GemsChangedPayload',
    version: 1,
  },
  'gamification:league_changed': {
    eventName: 'gamification:league_changed',
    description: 'La liga de un usuario ha cambiado',
    sourceModule: 'gamification',
    subscribes: ['dashboard'],
    payloadType: 'LeagueChangedPayload',
    version: 1,
  },
  'settings:settings_changed': {
    eventName: 'settings:settings_changed',
    description: 'La configuración global de la aplicación ha cambiado',
    sourceModule: 'settings',
    subscribes: ['sales', 'inventory'],
    payloadType: 'SettingsChangedPayload',
    version: 1,
  },
  'settings:tax_rate_changed': {
    eventName: 'settings:tax_rate_changed',
    description: 'La tasa de impuesto ha sido modificada',
    sourceModule: 'settings',
    subscribes: ['sales'],
    payloadType: 'TaxRateChangedPayload',
    version: 1,
  },
  'settings:license_activated': {
    eventName: 'settings:license_activated',
    description: 'Una licencia de DuoPOS ha sido activada',
    sourceModule: 'settings',
    subscribes: [],
    payloadType: 'LicenseActivatedPayload',
    version: 1,
  },
  'logistics:transfer_created': {
    eventName: 'logistics:transfer_created',
    description: 'Una transferencia de stock entre sucursales ha sido creada',
    sourceModule: 'logistics',
    subscribes: ['inventory', 'dashboard'],
    payloadType: 'TransferCreatedPayload',
    version: 1,
  },
  'logistics:transfer_completed': {
    eventName: 'logistics:transfer_completed',
    description: 'Una transferencia de stock ha sido completada',
    sourceModule: 'logistics',
    subscribes: ['inventory', 'dashboard'],
    payloadType: 'TransferCompletedPayload',
    version: 1,
  },
  'dashboard:dashboard_refresh': {
    eventName: 'dashboard:dashboard_refresh',
    description: 'Solicitud de actualización del tablero principal',
    sourceModule: 'dashboard',
    subscribes: ['dashboard'],
    payloadType: 'DashboardRefreshPayload',
    version: 1,
  },
};
